fun main() {
    var fila: EnfileiravelDinamica = FilaDinamica(11)
    fila.enfileirar("A")
    fila.enfileirar("B")
    fila.enfileirar("C")
    fila.enfileirar("D")
    fila.desenfileirar()
    fila.enfileirar("E")
    val conteudo = fila.desenfileirar()
    fila.enfileirar("F")
    println("Frente: ${fila.frente()}")
    fila.atualizar("X")
    println("Frente: ${fila.frente()}")
    fila.enfileirar("G")
    fila.enfileirar(conteudo)
    fila.enfileirar("I")
    fila.enfileirar("J")
    fila.enfileirar("K")
    println("Fila=${fila.imprimir()}")
}
