fun main(args: Array<String>) {
    var pilha: EmpilhavelDupla = PilhaDupla(14)
    pilha.empilhar1("Um")
    pilha.empilhar1("Dois")
    println("Topo:${pilha.topo1()}")
    pilha.empilhar2("Azul")
    pilha.empilhar2("Vermelho")
    pilha.empilhar1("Três")
    pilha.empilhar1("Quatro")
    println("Topo:${pilha.topo2()}")
    pilha.empilhar2("Verde")
    pilha.empilhar1("Cinco")
    pilha.empilhar2("Rosa")
    pilha.empilhar2("Preto")	
    pilha.empilhar1("Seis")	
    println("Topo:${pilha.topo1()}")
    val conteudo1 = pilha.desempilhar1()
    pilha.desempilhar1()
    pilha.empilhar2("Marrom")	
    pilha.empilhar1("Sete")
    pilha.empilhar1("Oito")
    println("Topo:${pilha.topo2()}")	
    val conteudo2 = pilha.desempilhar2()	
    pilha.empilhar1("Nove")    
    pilha.empilhar1(pilha.desempilhar1())
    pilha.desempilhar2();
    pilha.empilhar2("Cinza")	
    pilha.empilhar1(conteudo1)
    pilha.empilhar2(pilha.desempilhar2())
    pilha.empilhar2(conteudo2)
    println("Pilha1=${pilha.imprimir1()}")
    println("Pilha2=${pilha.imprimir2()}")			
}