fun main() {
	var fila: DeQueEnfileiravel = DeQueDinamica()
	fila.enfileirarInicio("A")
	println(fila.imprimirFrentePraTras()) 
	println(fila.tras())
	println(fila.frente()) 
	fila.enfileirarInicio("B")
	fila.desenfileirarFim()
    fila.enfileirarFim("c")
	fila.atualizarFim("C")
	fila.desenfileirarInicio()
	fila.enfileirarInicio("D") 
	println(fila.imprimirFrentePraTras()) 
	fila.frente()
	fila.desenfileirarFim()
	println(fila.imprimirFrentePraTras())
	println(fila.tras())    
	fila.enfileirarInicio("e")
	fila.atualizarInicio("E")    
	println(fila.imprimirFrentePraTras())
	fila.enfileirarFim("F")
	fila.desenfileirarInicio()
	fila.enfileirarFim("G")
	println(fila.tras()) 
	fila.enfileirarInicio("H")
	fila.desenfileirarFim()
	fila.enfileirarFim("I")
	println(fila.imprimirTrasPraFrente()) 
	fila.enfileirarInicio("J")
	fila.enfileirarFim("K")
	fila.enfileirarFim("L")
	println(fila.frente()) 
	fila.desenfileirarInicio()
	println(fila.imprimirFrentePraTras()) 

}